In [1]:
"""
what is Data Analysis ?

-> Data analysis is a process of inspecting, cleansing, transforming and modeling data with the goal of 
discovering useful information informing conclusions and supporting decision - making.


// Process :-

1. Asking Question
2. Data Wrangling 
3. Exploratory Data analysis 
4. Draw Conclusions 
5. Communicating Result (Report about your analysis)
"""


"""
// Data Wrangling or Munging or Preprocessing //

-> Data wrangling, sometimes referred to as data munging, is the process of transforming and mapping data from 
one "raw" data form into another format with the intent of make it more appropriate and valuable for a variety of  
downstream purposes such as analytics.

1.Gathering Data 

2.Assessing Data 

3.Cleaning Data 

"""

'\n// Data Wrangling or Munging or Preprocessing //\n\n-> Data wrangling, sometimes referred to as data munging, is the process of transforming and mapping data from \none "raw" data form into another format with the intent of make it more appropriate and valuable for a variety of  \ndownstream purposes such as analytics.\n\n1.Gathering Data \n\n2.Assessing Data \n\n3.Cleaning Data \n\n'

In [2]:
"""
// Data Gathering //

import From :-

Database, CSV, Excel , text , Json 


Export from :

CSV, Json Excel, Database, Html


API and Web Scraping !
"""

'\n// Data Gathering //\n\nimport From :-\n\nDatabase, CSV, Excel , text , Json \n\n\nExport from :\n\nCSV, Json Excel, Database, Html\n\n\nAPI and Web Scraping !\n'

# 1. Data Gathering :-

### Importing from CSV :-

In [3]:
import pandas as pd

In [4]:
# Opening with local csv file.

imdb = pd.read_csv('D:\LEARNING\imdb.csv')
imdb.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [5]:
# Opening a csv file from an URL(uniform Resource Locator).

# The library used to fetch the data from the URL is requests, 
# which allows us to send HTTP requests and handle responses.
import requests
from io import StringIO as str 

# The URL of the CSV file to be fetched.
url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
response = requests.get(url, headers=headers)
data = str(response.text) # StringIO is used to read the response text as a file-like object.

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [6]:
# Sep Parameter :- for tsv file (tab separated values).
# name parameter -> to give a name to the column of the data frame.

pd.read_csv('D:\LEARNING\sep.tsv', sep='\t', names=['ID', 'Name', 'Age', 'City'])

      ID   Name  Age   City
0     id   name  age  score
1      1  AKIDP   24     56
2      2  HSSXF   29     76
3      3  GVDNZ   27     50
4      4  HGGUP   26     98
..   ...    ...  ...    ...
96    96  DELTC   18     75
97    97  UUTOY   30     95
98    98  OKONU   22     55
99    99  BWNRV   27     79
100  100  TWGBB   22     66

[101 rows x 4 columns]

In [7]:
# Index_col parameter -> to set a specific column as the index of the DataFrame.

pd.read_csv('D:\LEARNING\imdb.csv', index_col='Series_Title')

,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Series_Title,,,,,,,,,
The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...
Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [8]:
# Header parameter -> to specify the row number to use as the column names, 
# or to indicate that there is no header row.

pd.read_csv('D:\LEARNING\imdb.csv', header=1)

,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
0,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
1,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
2,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
3,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
4,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
...,...,...,...,...,...,...,...,...,...,...
994,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
995,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
996,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
997,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
998,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [9]:
# usecols parameter -> to specify a subset of columns(Jo Jo cols chahiye mujhe) to read from the CSV file.

pd.read_csv('D:\LEARNING\imdb.csv', usecols=['Series_Title', 'IMDB_Rating'])

                 Series_Title  IMDB_Rating
0    The Shawshank Redemption          9.3
1               The Godfather          9.2
2             The Dark Knight          9.0
3      The Godfather: Part II          9.0
4                12 Angry Men          9.0
..                        ...          ...
995    Breakfast at Tiffany's          7.6
996                     Giant          7.6
997     From Here to Eternity          7.6
998                  Lifeboat          7.6
999              The 39 Steps          7.6

[1000 rows x 2 columns]

In [10]:
# squeeze parameter but now it become function -> to reduce the dimensionality of the returned object when possible.
# also for convert the data frame into a series if the data frame has only one column.

pd.read_csv('D:\LEARNING\imdb.csv', usecols=['Series_Title']).squeeze()

0      The Shawshank Redemption
1                 The Godfather
2               The Dark Knight
3        The Godfather: Part II
4                  12 Angry Men
                 ...
995      Breakfast at Tiffany's
996                       Giant
997       From Here to Eternity
998                    Lifeboat
999                The 39 Steps
Name: Series_Title, Length: 1000, dtype: object

In [11]:
# skiprows/nrows parameter :
# nrows -> to specify the number of rows to read from the CSV file.

pd.read_csv('D:\LEARNING\practice_df.csv', nrows=50)

     Name  Age       City  Salary
0   Sneha   42       Pune  115999
1    Neha   31    Chennai   47955
2   Rohit   36      Delhi   67841
3   Arjun   36    Kolkata  100640
4   Sneha   21    Kolkata   95510
5   Vikas   29    Chennai   64911
6   Priya   48  Bangalore   89031
7   Sneha   47  Hyderabad  118726
8   Rohit   26  Hyderabad   37357
9   Arjun   36    Chennai   62479
10   Neha   49     Mumbai   91476
11  Rohit   23     Mumbai   74811
12  Rohit   40  Hyderabad   66208
13  Priya   48  Hyderabad   50150
14  Karan   47    Kolkata  101180
15  Arjun   24  Bangalore   73286
16  Rahul   39      Delhi   98450
17  Rohit   46     Mumbai   51352
18  Karan   23  Hyderabad   85069
19  Rahul   39    Kolkata   44397
20  Arjun   40       Pune   71555
21   Amit   27    Kolkata   76959
22  Vikas   40     Mumbai   30728
23  Karan   29     Mumbai   80517
24  Pooja   21    Kolkata   96234
25   Amit   28      Delhi   69954
26  Vikas   27    Chennai   77280
27  Priya   38     Mumbai  109459
28  Sneha   28    Kolkata   46779
29   Neha   21  Hyderabad   93932
30  Pooja   31    Kolkata  102936
31  Priya   48  Bangalore   54466
32  Arjun   45    Chennai   66939
33  Priya   45       Pune   99896
34  Sneha   38      Delhi   65270
35  Arjun   43       Pune   89163
36  Pooja   30    Chennai  112637
37  Sneha   23    Chennai   81934
38  Rahul   27    Chennai   94895
39   Neha   48       Pune   62307
40  Pooja   36  Hyderabad   84098
41  Rahul   46    Chennai   90921
42  Vikas   36    Kolkata   35486
43  Pooja   45       Pune   38335
44  Vikas   40    Chennai  116900
45  Arjun   48    Kolkata  119112
46  Rahul   37  Hyderabad   41130
47   Neha   22  Bangalore  117508
48  Sneha   21  Hyderabad   90566
49  Rohit   36    Chennai   96703

In [12]:
# Encoding parameter -> to specify the encoding of the CSV file, 
# which is important for correctly reading files with special characters or non-ASCII text.

pd.read_csv('D:\LEARNING\imdb.csv', encoding='latin-1')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [13]:
# skip bad lines :

pd.read_csv('D:\\LEARNING\\imdb.csv', on_bad_lines='skip') # on_bad_lines='skip' in newer versions of pandas

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [14]:
# dtype parameter :

pd.read_csv('D:\\LEARNING\\imdb.csv', dtype={'Runtime': float}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Runtime        1000 non-null   float64
 3   Genre          1000 non-null   object
 4   IMDB_Rating    1000 non-null   float64
 5   Director       1000 non-null   object
 6   Star1          1000 non-null   object
 7   No_of_Votes    1000 non-null   int64
 8   Gross          1000 non-null   float64
 9   Metascore      843 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 78.3+ KB

In [15]:
# Handling Dates :-
# parse_dates parameter

pd.read_csv('D:\LEARNING\ipl-matches.csv', parse_dates=['Date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    datetime64[ns]
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(17)
memory usage: 148.6+ KB

In [16]:
# convertors :-

# function :
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name
    
pd.read_csv('D:\LEARNING\ipl-matches.csv', converters={'Team1': rename})

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,RCB,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,RCB,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,RCB,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [17]:
# na_values parameter : jis jis word jo NaN consider krne chahte ho.

pd.read_csv("D:\LEARNING\imdb.csv", na_values=['Drama'])

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,NaN,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,NaN,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,NaN,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,NaN,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [18]:
# Loading a huge dataset in chunks :

dfs = pd.read_csv("D:\LEARNING\movies.csv", chunksize=400)

# for print the dataset chunks you need to use For loop

for chunk in dfs:
    print(chunk.shape)

(400, 18)
(400, 18)
(400, 18)
(400, 18)
(29, 18)

# Importing From Excel(.xlsx)

In [19]:
# Reading file from Excel :- Other parameter are same as csv, more or less.

# this is for sheet 1 will print
pd.read_excel("D:\\LEARNING\\ipl_matches_sample_220.xlsx").info()



# for other sheet you need to print then use parameter sheet_name
# pd.read_excel("D:\\LEARNING\\ipl_matches_sample_220.xlsx", sheet_name="").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               220 non-null    int64
 1   City             214 non-null    object
 2   Date             220 non-null    object
 3   Season           220 non-null    object
 4   MatchNumber      220 non-null    object
 5   Team1            220 non-null    object
 6   Team2            220 non-null    object
 7   Venue            220 non-null    object
 8   TossWinner       220 non-null    object
 9   TossDecision     220 non-null    object
 10  SuperOver        219 non-null    object
 11  WinningTeam      219 non-null    object
 12  WonBy            220 non-null    object
 13  Margin           215 non-null    float64
 14  method           6 non-null      object
 15  Player_of_Match  219 non-null    object
 16  Team1Players     220 non-null    object
 17  Team2Players     220 non-null    object
 18  Umpire1          220 non-null    object
 19  Umpire2          220 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 34.5+ KB

# Importing Reading text files :

In [20]:
# You will use read_csv function in this too .

pd.read_csv("D:\LEARNING\Reading_file.txt")

,ID,Name,Age,City,Score 1,Karan,22,Jaipur,60 2,Ravi,24,Jaipur.1,61
0,3,Amit,35,Delhi,68 4,Priya,24.0,Jaipur,69 5,Priya,37.0,Chennai,50.0
1,6,Meena,19,Kolkata,83 7,Amit,18.0,Patna,70 8,Meena,32.0,Mumbai,78.0
2,9,Amit,23,Kolkata,96 10,John,24.0,Kolkata,68 11,Arjun,33.0,Chennai,100.0
3,12,Isha,21,Patna,86 13,Amit,26.0,Chennai,54 14,John,32.0,Kolkata,85.0
4,15,Meena,22,Chennai,54 16,Karan,26.0,Lucknow,91 17,Neha,20.0,Kolkata,85.0
5,18,Meena,29,Patna,58 19,Priya,20.0,Mumbai,68 20,Amit,27.0,Lucknow,65.0
6,21,Arjun,22,Lucknow,94 22,Meena,19.0,Mumbai,72 23,Amit,23.0,Mumbai,54.0
7,24,Priya,31,Patna,79 25,Amit,36.0,Mumbai,84 26,John,20.0,Kolkata,52.0
8,27,Amit,29,Patna,95 28,Meena,29.0,Chennai,59 29,Karan,27.0,Lucknow,68.0
9,30,Ravi,19,Patna,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Importing JSON/SQL :-

In [21]:
import pandas as pd 

pd.read_json("D:\LEARNING\\train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [22]:
import mysql.connector